package ar.com.catgis.service;

import java.io.*;

/**
 * Configuration for pg_featureserv - PostGIS-based feature service.
 * Generates a configuration file for pg_featureserv deployment.
 */
public final class PgFeatureservConfig {

    private PgFeatureservConfig() {}

    public record Config(
            String databaseUrl,
            String schema,
            int port,
            boolean cors,
            String title
    ) {}

    public static Config defaultConfig() {
        return new Config(
                "postgres://localhost:5432/catgis",
                "public",
                3000,
                true,
                "CATGIS Feature Service"
        );
    }

    /**
     * Generate a pg_featureserv configuration file.
     */
    public static String generateConfig(Config config) {
        StringBuilder sb = new StringBuilder();
        sb.append("# pg_featureserv configuration for CATGIS\n");
        sb.append("# Generated by CATGIS Desktop\n\n");
        sb.append("[database]\n");
        sb.append("connection_string = \"").append(config.databaseUrl()).append("\"\n");
        sb.append("schema = \"").append(config.schema()).append("\"\n\n");
        sb.append("[server]\n");
        sb.append("port = ").append(config.port()).append("\n");
        sb.append("cors = ").append(config.cors()).append("\n");
        sb.append("title = \"").append(config.title()).append("\"\n");
        return sb.toString();
    }

    /**
     * Write configuration to file.
     */
    public static void writeConfig(Config config, File outputFile) throws IOException {
        try (PrintWriter pw = new PrintWriter(new FileWriter(outputFile))) {
            pw.print(generateConfig(config));
        }
    }
}
