package ar.com.catgis.service;

import java.io.*;

/**
 * Configuration for pg_tileserv - PostGIS-based vector tile server.
 * Generates a configuration file for pg_tileserv deployment.
 */
public final class PgTileservConfig {

    private PgTileservConfig() {}

    public record Config(
            String databaseUrl,
            String schema,
            int port,
            boolean verbose,
            String basemap
    ) {}

    public static Config defaultConfig() {
        return new Config(
                "postgres://localhost:5432/catgis",
                "public",
                7800,
                false,
                "osm"
        );
    }

    /**
     * Generate a pg_tileserv configuration file.
     */
    public static String generateConfig(Config config) {
        StringBuilder sb = new StringBuilder();
        sb.append("# pg_tileserv configuration for CATGIS\n");
        sb.append("# Generated by CATGIS Desktop\n\n");
        sb.append("[database]\n");
        sb.append("connection_string = \"").append(config.databaseUrl()).append("\"\n");
        sb.append("schema = \"").append(config.schema()).append("\"\n\n");
        sb.append("[server]\n");
        sb.append("port = ").append(config.port()).append("\n");
        sb.append("verbose = ").append(config.verbose()).append("\n\n");
        sb.append("[basemap]\n");
        sb.append("type = \"").append(config.basemap()).append("\"\n");
        return sb.toString();
    }

    /**
     * Write configuration to file.
     */
    public static void writeConfig(Config config, File outputFile) throws IOException {
        try (PrintWriter pw = new PrintWriter(new FileWriter(outputFile))) {
            pw.print(generateConfig(config));
        }
    }
}
